export default {
  // VUE_CONFIG_CLIENT_TYPE_KEY: ,
  // //VUE_CONFIG_APP_KEY: "",
  // VUE_CONFIG_APP_KEY: "",
  // //VUE_CONFIG_APP_KEY: "",
  VUE_CONFIG_API: "https://localhost:7020",
  // //VUE_CONFIG_API:"",
  // VUE_CONFIG_IDENTITY_API: "",
  // //VUE_CONFIG_IDENTITY_API: "",
  VUE_CONFIG_SYSTEM_NAME: "InmunoEnsayo",
  // VUE_CONFIG_CDN: "",
  // VUE_CONFIG_CDN_ROOT_FOLDER: "",
  // VUE_CONFIG_CLIENT_LOGIN_LATERAL_IMAGE: "",
  // VUE_CONFIG_CLIENT_SECOND_LOGO: "",
  // VUE_CONFIG_CLIENT_LOGO: "",
  // VUE_CONFIG_CLIENT_AI_ENABLE: false
}
